from .muse_minimax_director import (
    NODE_CLASS_MAPPINGS as _DIRECTOR_NODE_CLASS_MAPPINGS,
    NODE_DISPLAY_NAME_MAPPINGS as _DIRECTOR_NODE_DISPLAY_NAME_MAPPINGS,
)
from .muse_model_route import (
    NODE_CLASS_MAPPINGS as _MODEL_ROUTE_NODE_CLASS_MAPPINGS,
    NODE_DISPLAY_NAME_MAPPINGS as _MODEL_ROUTE_NODE_DISPLAY_NAME_MAPPINGS,
)

NODE_CLASS_MAPPINGS = {**_DIRECTOR_NODE_CLASS_MAPPINGS, **_MODEL_ROUTE_NODE_CLASS_MAPPINGS}
NODE_DISPLAY_NAME_MAPPINGS = {
    **_DIRECTOR_NODE_DISPLAY_NAME_MAPPINGS,
    **_MODEL_ROUTE_NODE_DISPLAY_NAME_MAPPINGS,
}

WEB_DIRECTORY = "./js"

__all__ = ["NODE_CLASS_MAPPINGS", "NODE_DISPLAY_NAME_MAPPINGS", "WEB_DIRECTORY"]
